sudo: required
language: generic

services:
  - docker
env:
  - TRAVIS_DEBIAN_DISTRIBUTION=stretch
  - TRAVIS_DEBIAN_BACKPORTS=true 

script:
  - sh script.sh

branches:
  except:
    - /^debian\/\d/
