sudo: required
language: generic

services:
  - docker
env:
  - TRAVIS_DEBIAN_DISTRIBUTION=buster TRAVIS_DEBIAN_EXTRA_REPOSITORY_GPG_URL=https://pkg.yeti-switch.org/key.gpg

script:
  - sh script.sh

branches:
  except:
    - /^debian\/\d/
